name: Test
on:
  push:
  pull_request:
  schedule: [{ cron: "0 0 10 * *" }] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:

permissions: {}
jobs:
  test:
    uses: nodenv/.github/.github/workflows/test.yml@v7.0.8
    with: { npm: false }
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write

  checksums:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with: { egress-policy: audit }
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # need history for lint:checksums
          persist-credentials: false
      - run: npm ci

        # FIXME workaround https://github.com/actions/checkout/issues/910
      - if: github.event_name == 'pull_request'
        run: npm run lint:checksums -- "origin/${GITHUB_BASE_REF}"
      - run: npm run lint:checksums -- HEAD^
        if: github.event_name == 'push'
